# docker-compose.yml
services:
  # Banco de dados
  db:
    image: postgres
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=datawarehouse
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Inicialização do banco com script SQL
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d datawarehouse"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API para acesso aos dados
  api:
    build: ./api
    container_name: api-lanchonete
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/datawarehouse
      

    ports:
      - "8000:8000"

  app:
    build: ./app
    container_name: app-client
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    ports:
      - "8081:8081"

  app-admin:
    build: ./app-adm
    container_name: app-adm
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    ports:
      - "8082:8082"

volumes:
  postgres_data: